CREATE TABLE PLAYER 
(
  ID INTEGER NOT NULL 
, NAME VARCHAR2(10) NOT NULL 
, GENDER VARCHAR2(2) NOT NULL 
, AGE INTEGER NOT NULL 
, ID_NUMBER CHAR(18) NOT NULL 
, REGION VARCHAR2(20) 
, TELEPHONE_NUMBER INTEGER 
, CONSTRAINT PLAYER_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

COMMENT ON COLUMN PLAYER.ID IS '选手ID';

COMMENT ON COLUMN PLAYER.NAME IS '姓名';

COMMENT ON COLUMN PLAYER.GENDER IS '性别';

COMMENT ON COLUMN PLAYER.AGE IS '年龄';

COMMENT ON COLUMN PLAYER.ID_NUMBER IS '身份证号';

COMMENT ON COLUMN PLAYER.REGION IS '地区，如：广东广州';

COMMENT ON COLUMN PLAYER.TELEPHONE_NUMBER IS '联系方式';

CREATE TABLE EVENT 
(
  ID INTEGER NOT NULL 
, CATEGORY VARCHAR2(20) NOT NULL 
, NAME VARCHAR2(20) NOT NULL 
, START_DATE DATE NOT NULL 
, END_DATE DATE NOT NULL 
, EVENT_DATE DATE NOT NULL 
, CONSTRAINT EVENT_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

COMMENT ON COLUMN EVENT.ID IS '赛事id';

COMMENT ON COLUMN EVENT.CATEGORY IS '赛事类型（全马、半马）';

COMMENT ON COLUMN EVENT.NAME IS '赛事名称，如：苏州太湖马拉松';

COMMENT ON COLUMN EVENT.START_DATE IS '报名开始时间';

COMMENT ON COLUMN EVENT.END_DATE IS '报名结束时间';

COMMENT ON COLUMN EVENT.EVENT_DATE IS '正式比赛时间';
