/*4、prize表*/
CREATE TABLE PRIZE 
(
  PRIZE_ID NUMBER(*, 0) NOT NULL , 
ITEM VARCHAR2(20 BYTE) NOT NULL ,
CONSTRAINT PRIZE_PK PRIMARY KEY (PRIZE_ID)
);

/*5、volunteer表 未建立外码约束*/
CREATE TABLE VOLUNTEER 
(
  ID NUMBER(*, 0) NOT NULL , 
TELEPHONE_NUMBER NUMBER(*, 0) , 
NAME VARCHAR2(20 BYTE) , 
SUPPLYPOINT_ID NUMBER(*, 0) , 
MEDICALPOINT_ID NUMBER(*, 0) , 
CONSTRAINT VOLUNTEER_PK PRIMARY KEY (ID )
);

/*6、photographer表*/
CREATE TABLE PHOTOGRAPHER 
(
  ID INTEGER NOT NULL , 
NAME VARCHAR(10) NOT NULL , 
CONSTRAINT PHOTOGRAPHER_PK PRIMARY KEY (ID )
);

/*14、resulttoprize表 未建立外码约束*/
CREATE TABLE RESULTTOPRIZE 
(
  GENDER_RANK INTEGER NOT NULL , 
EVENT_ID INTEGER NOT NULL , 
PRIZE_ID INTEGER NOT NULL , 
CONSTRAINT RESULTTOPRIZE_PK PRIMARY KEY (GENDER_RANK , EVENT_ID )
);

/*15、event_item 未建立外码约束*/
CREATE TABLE EVENT_ITEM 
(
  EVENT_ID INTEGER NOT NULL , 
ITEM_ID INTEGER NOT NULL , 
TYPE VARCHAR(20) NOT NULL , 
CONSTRAINT EVENT_ITEM_PK PRIMARY KEY (EVENT_ID , ITEM_ID)
); 

/*16、schedule 未建立外码约束*/
CREATE TABLE SCHEDULE 
(
  EVENT_ID INTEGER NOT NULL , 
VOLUNTEER_ID INTEGER NOT NULL , 
COLUMN1 VARCHAR(20) NOT NULL , 
CONSTRAINT SCHEDULE_PK PRIMARY KEY (EVENT_ID , VOLUNTEER_ID )
);

/*17、drive表*/
CREATE TABLE DRIVE 
(
  VOLUNTEER_ID INTEGER NOT NULL , 
SHUTTLECAR INTEGER NOT NULL , 
CONSTRAINT DRIVE_PK PRIMARY KEY (VOLUNTEER_ID , SHUTTLECAR )
);
